---
abstract: 'Bio-Tradis contains a set of tools to analyse the output from TraDIS analyses. For more information on the TraDIS method, see http://genome.cshlp.org/content/19/12/2308'
author:
  - 'Carla Cummins <cc21@sanger.ac.uk>'
build_requires:
  Env::Path: 0
  File::Slurp: 0
  Test::Most: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.120921'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Tradis
requires:
  Bio::DB::Sam: 0
  Bio::Seq: 0
  Cwd: 0
  Data::Dumper: 0
  Exception::Class: 0
  File::Temp: 0
  Getopt::Long: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  homepage: http://www.sanger.ac.uk/
  repository: https://github.com/sanger-pathogens/Bio-Tradis.git
version: 1.132190
